name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem -r dist/todo-app-ui/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Move files into nginx folder
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo rm -rf /var/www/html/*
            sudo mv /home/ubuntu/* /var/www/html/
            sudo systemctl restart nginx
          EOF
